language: php

php:
  - hhvm
  - 7.0

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - composer install --dev --prefer-source

script: ./vendor/bin/phpunit
