language: php

notifications:
  email:
    recipients:
      - daniel@unfun.co

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - phpenv config-rm xdebug.ini || true

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - composer update
  - sh -c "cd ext/bijective && phpize && ./configure && make && make install"
  - echo "extension=bijective.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  - vendor/bin/phpunit

sudo: false
